// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdTe5XfsR0h8zGv2FcJl6TEQsOH6W2lss',
    appId: '1:11221154319:android:94541b9a2764056de4417a',
    messagingSenderId: '11221154319',
    projectId: 'fir-demo-f5f77',
    storageBucket: 'fir-demo-f5f77.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAt5LDFN0n-Y6g5agTUPaURGiEaP8FU1Ic',
    appId: '1:11221154319:ios:572b3e92aee2d2e9e4417a',
    messagingSenderId: '11221154319',
    projectId: 'fir-demo-f5f77',
    storageBucket: 'fir-demo-f5f77.appspot.com',
    androidClientId: '11221154319-useqi8gvbonvor9bh2tpnhfv7e6j5auc.apps.googleusercontent.com',
    iosClientId: '11221154319-p7a91b9hvo2ldvgh7esquff1jpiootaf.apps.googleusercontent.com',
    iosBundleId: 'com.example.authWithOtp',
  );

}